// <auto-generated />
using System;
using FilmAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmAPI.Migrations
{
    [DbContext(typeof(FilmDbContext))]
    [Migration("20260512085650_TicketTypes")]
    partial class TicketTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FilmAPI.Model.Biglietto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BarcodeValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CodiceBiglietto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OrdineId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrezzoBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PrezzoTotale")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SalaPostoId")
                        .HasColumnType("int");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<decimal>("Supplemento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TipoBiglietto")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidatoAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ValidatoCinemaId")
                        .HasColumnType("int");

                    b.Property<int?>("ValidatoDaUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodiceBiglietto")
                        .IsUnique();

                    b.HasIndex("OrdineId");

                    b.HasIndex("SalaPostoId");

                    b.HasIndex("UserId");

                    b.HasIndex("ValidatoCinemaId");

                    b.HasIndex("ValidatoDaUserId");

                    b.HasIndex("ShowId", "SalaPostoId")
                        .IsUnique();

                    b.ToTable("Biglietti");
                });

            modelBuilder.Entity("FilmAPI.Model.CampaignConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GiorniPrima")
                        .HasColumnType("int");

                    b.Property<int?>("Giorno")
                        .HasColumnType("int");

                    b.Property<int?>("Mese")
                        .HasColumnType("int");

                    b.Property<string>("MessaggioPersonalizzato")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PercentualeSconto")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UltimaEsecuzione")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("CampaignConfigs");
                });

            modelBuilder.Entity("FilmAPI.Model.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("FilmAPI.Model.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CodiceLocale")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<double?>("Latitudine")
                        .HasColumnType("double");

                    b.Property<double?>("Longitudine")
                        .HasColumnType("double");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");
                });

            modelBuilder.Entity("FilmAPI.Model.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CastText")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("CopertinaPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("DataProduzione")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly?>("DataRilascio")
                        .HasColumnType("date");

                    b.Property<string>("DescrizioneLunga")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Durata")
                        .HasColumnType("int");

                    b.Property<string>("FilmatoPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RegistaId")
                        .HasColumnType("int");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RegistaId");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("FilmAPI.Model.FilmCategoria", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.HasKey("FilmId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("FilmCategorie");
                });

            modelBuilder.Entity("FilmAPI.Model.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("ImmaginePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("FilmAPI.Model.FoodOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrdineId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("OrdineId");

                    b.ToTable("FoodOrderItems");
                });

            modelBuilder.Entity("FilmAPI.Model.GiftCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcquirenteUserId")
                        .HasColumnType("int");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataAcquisto")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataInvioProgrammato")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRiscatto")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DestinatarioEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("InviataIl")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Messaggio")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("OrdineId")
                        .HasColumnType("int");

                    b.Property<int?>("RiscattataDaUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoResiduo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<decimal>("ValoreIniziale")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AcquirenteUserId");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.HasIndex("OrdineId");

                    b.HasIndex("RiscattataDaUserId");

                    b.HasIndex("Stato");

                    b.ToTable("GiftCards");
                });

            modelBuilder.Entity("FilmAPI.Model.ManualRefundReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("OrdineId")
                        .HasColumnType("int");

                    b.Property<int>("ReasonCode")
                        .HasColumnType("int");

                    b.Property<int?>("Resolution")
                        .HasColumnType("int");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ShowCancellationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdineId");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("ShowCancellationId");

                    b.ToTable("ManualRefundReviews");
                });

            modelBuilder.Entity("FilmAPI.Model.MembershipCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AttivataIl")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Cap")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Citta")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataIscrizione")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataNascita")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataScadenzaAbbonamento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAttiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<decimal>("PuntiDisponibili")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PuntiTotali")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("QrCodeData")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Via")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MembershipCards");
                });

            modelBuilder.Entity("FilmAPI.Model.MerchItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ImmaginePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("MerchItems");
                });

            modelBuilder.Entity("FilmAPI.Model.MerchOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodiceOrdine")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Totale")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodiceOrdine")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("MerchOrders");
                });

            modelBuilder.Entity("FilmAPI.Model.MerchOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MerchItemId")
                        .HasColumnType("int");

                    b.Property<int>("MerchOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MerchItemId");

                    b.HasIndex("MerchOrderId", "MerchItemId")
                        .IsUnique();

                    b.ToTable("MerchOrderItems");
                });

            modelBuilder.Entity("FilmAPI.Model.MovimentoCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CinemaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("OperatoreUserId")
                        .HasColumnType("int");

                    b.Property<int?>("OrdineId")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoPost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SaldoPre")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.HasIndex("OperatoreUserId");

                    b.HasIndex("OrdineId");

                    b.HasIndex("UserId");

                    b.ToTable("MovimentiCredito");
                });

            modelBuilder.Entity("FilmAPI.Model.NewsletterScheduled", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenuto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Inviati")
                        .HasColumnType("int");

                    b.Property<string>("Oggetto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Totale")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NewsletterScheduleds");
                });

            modelBuilder.Entity("FilmAPI.Model.NewsletterSubscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodiceSconto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("IscrittoIl")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("ScontoUsato")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CodiceSconto")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NewsletterSubscribers");
                });

            modelBuilder.Entity("FilmAPI.Model.Ordine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckoutCompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CheckoutExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<string>("CodiceOrdine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CreditoRiservato")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("DiscountCode")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<string>("HoldToken")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<decimal>("ImportoCarta")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ImportoCredito")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("LastPaymentError")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("NumeroBiglietti")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<int?>("ScontoPercent")
                        .HasColumnType("int");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<string>("StripeCheckoutSessionId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("TicketEmailLastError")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("TicketEmailSentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotaleLordo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.HasIndex("CodiceOrdine")
                        .IsUnique();

                    b.HasIndex("FilmId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("SalaId");

                    b.HasIndex("ShowId");

                    b.HasIndex("UserId");

                    b.ToTable("Ordini");
                });

            modelBuilder.Entity("FilmAPI.Model.OrdineRefund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreditRefundMovementId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal>("ImportoCarta")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ImportoCredito")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("OrdineId")
                        .HasColumnType("int");

                    b.Property<int>("ShowCancellationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeRefundId")
                        .HasColumnType("longtext");

                    b.Property<string>("StripeRefundStatus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrdineId");

                    b.HasIndex("ShowCancellationId");

                    b.ToTable("OrdineRefunds");
                });

            modelBuilder.Entity("FilmAPI.Model.PartyBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletatoIl")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ConfermatoIl")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FilmId")
                        .HasColumnType("int");

                    b.Property<string>("NomeFesta")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("NumeroOspiti")
                        .HasColumnType("int");

                    b.Property<DateTime>("OraFine")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("OraInizio")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("OrdineId")
                        .HasColumnType("int");

                    b.Property<int>("Pacchetto")
                        .HasColumnType("int");

                    b.Property<string>("QrCodeData")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RichiesteSpeciali")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Totale")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.HasIndex("FilmId");

                    b.HasIndex("OrdineId");

                    b.HasIndex("UserId");

                    b.ToTable("PartyBookings");
                });

            modelBuilder.Entity("FilmAPI.Model.PartyFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PartyBookingId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartyBookingId");

                    b.ToTable("PartyFeedbacks");
                });

            modelBuilder.Entity("FilmAPI.Model.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("Used")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("FilmAPI.Model.Premio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("CostoPunti")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ImmaginePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("QuantitaDisponibile")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valore")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Attivo");

                    b.ToTable("Premi");
                });

            modelBuilder.Entity("FilmAPI.Model.PremioRiscatto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataRiscatto")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataScadenza")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataUtilizzo")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("PremioId")
                        .HasColumnType("int");

                    b.Property<decimal>("PuntiSpesi")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.HasIndex("PremioId");

                    b.HasIndex("UserId");

                    b.ToTable("PremiRiscatti");
                });

            modelBuilder.Entity("FilmAPI.Model.Prenotazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPrenotazione")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("NumeroPosti")
                        .HasColumnType("int");

                    b.Property<int>("ProiezioneId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProiezioneId");

                    b.HasIndex("UserId");

                    b.ToTable("Prenotazioni");
                });

            modelBuilder.Entity("FilmAPI.Model.Proiezione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ora")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("CinemaId", "FilmId", "Data", "Ora")
                        .IsUnique();

                    b.ToTable("Proiezioni");
                });

            modelBuilder.Entity("FilmAPI.Model.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("DiscountCode")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("MaxUsage")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("Priority");

                    b.HasIndex("StartDate");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("FilmAPI.Model.PuntiMovimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MembershipCardId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("Punti")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("RiferimentoId")
                        .HasColumnType("int");

                    b.Property<string>("RiferimentoTipo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("SaldoPost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SaldoPre")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("MembershipCardId");

                    b.HasIndex("UserId");

                    b.ToTable("PuntiMovimenti");
                });

            modelBuilder.Entity("FilmAPI.Model.ReferralCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ReferralCodes");
                });

            modelBuilder.Entity("FilmAPI.Model.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "DeviceId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FilmAPI.Model.Regista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nazionalita")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Registi");
                });

            modelBuilder.Entity("FilmAPI.Model.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAttiva")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumeroProgressivo")
                        .HasColumnType("int");

                    b.Property<decimal>("Supplemento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TipoSala")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId", "NumeroProgressivo")
                        .IsUnique();

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("FilmAPI.Model.SalaPosto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Fila")
                        .HasColumnType("int");

                    b.Property<bool>("IsAttivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsWheelchair")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int?>("PosX")
                        .HasColumnType("int");

                    b.Property<int?>("PosY")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<string>("Settore")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SalaId", "Settore", "Fila", "Numero")
                        .IsUnique();

                    b.ToTable("SalaPosti");
                });

            modelBuilder.Entity("FilmAPI.Model.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<int>("DurataMinutiSnapshot")
                        .HasColumnType("int");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrezzoBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<decimal>("SupplementoSala")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("SalaId");

                    b.HasIndex("StartAtUtc");

                    b.HasIndex("CinemaId", "SalaId", "StartAtUtc")
                        .IsUnique();

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("FilmAPI.Model.ShowCancellation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BigliettiTotali")
                        .HasColumnType("int");

                    b.Property<DateTime>("CancelledAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CancelledByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EmailsInviate")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("EmailsInviateIl")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("ManualReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("OrdiniTotali")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("RimborsiFalliti")
                        .HasColumnType("int");

                    b.Property<int>("RimborsiRiusciti")
                        .HasColumnType("int");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotaleCarta")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotaleCredito")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotaleDaRimborsare")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("ShowId");

                    b.ToTable("ShowCancellations");
                });

            modelBuilder.Entity("FilmAPI.Model.ShowPostoStato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HoldToken")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int?>("OrdineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SalaPostoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScadeAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ShowId")
                        .HasColumnType("int");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<int?>("TicketType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HoldToken");

                    b.HasIndex("OrdineId");

                    b.HasIndex("SalaPostoId");

                    b.HasIndex("ScadeAtUtc");

                    b.HasIndex("UserId");

                    b.HasIndex("ShowId", "SalaPostoId")
                        .IsUnique();

                    b.ToTable("ShowPostiStato");
                });

            modelBuilder.Entity("FilmAPI.Model.SupportConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("SupportConversations");
                });

            modelBuilder.Entity("FilmAPI.Model.SupportMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("SupportMessages");
                });

            modelBuilder.Entity("FilmAPI.Model.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminResolutionNote")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<int?>("AssignedAdminUserId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("ContextMetadata")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ContextOrderCode")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("ContextPage")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAdminUserId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ConversationId");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("FilmAPI.Model.SupportTicketAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("varchar(1200)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("TicketId");

                    b.ToTable("SupportTicketAudits");
                });

            modelBuilder.Entity("FilmAPI.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AnonymizedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("AuthVersion")
                        .HasColumnType("int");

                    b.Property<int?>("CinemaPreferitoId")
                        .HasColumnType("int");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("CreditoResiduo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastLoginProvider")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("LocalCredentialsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Ruolo")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CinemaPreferitoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FilmAPI.Model.UserCinemaAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanManageShows")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanTopUpCredit")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanValidateTickets")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinemaId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CinemaId")
                        .IsUnique();

                    b.ToTable("UserCinemaAssignments");
                });

            modelBuilder.Entity("FilmAPI.Model.Biglietto", b =>
                {
                    b.HasOne("FilmAPI.Model.Ordine", "Ordine")
                        .WithMany("Biglietti")
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.SalaPosto", "SalaPosto")
                        .WithMany()
                        .HasForeignKey("SalaPostoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Show", "Show")
                        .WithMany("Biglietti")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany("Biglietti")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Cinema", "ValidatoCinema")
                        .WithMany()
                        .HasForeignKey("ValidatoCinemaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FilmAPI.Model.User", "ValidatoDaUser")
                        .WithMany()
                        .HasForeignKey("ValidatoDaUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ordine");

                    b.Navigation("SalaPosto");

                    b.Navigation("Show");

                    b.Navigation("User");

                    b.Navigation("ValidatoCinema");

                    b.Navigation("ValidatoDaUser");
                });

            modelBuilder.Entity("FilmAPI.Model.Film", b =>
                {
                    b.HasOne("FilmAPI.Model.Regista", "Regista")
                        .WithMany("Films")
                        .HasForeignKey("RegistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regista");
                });

            modelBuilder.Entity("FilmAPI.Model.FilmCategoria", b =>
                {
                    b.HasOne("FilmAPI.Model.Categoria", "Categoria")
                        .WithMany("FilmCategorie")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Film", "Film")
                        .WithMany("FilmCategorie")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("FilmAPI.Model.FoodOrderItem", b =>
                {
                    b.HasOne("FilmAPI.Model.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Ordine", "Ordine")
                        .WithMany()
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Ordine");
                });

            modelBuilder.Entity("FilmAPI.Model.GiftCard", b =>
                {
                    b.HasOne("FilmAPI.Model.User", "AcquirenteUser")
                        .WithMany()
                        .HasForeignKey("AcquirenteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FilmAPI.Model.Ordine", "Ordine")
                        .WithMany()
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FilmAPI.Model.User", "RiscattataDaUser")
                        .WithMany()
                        .HasForeignKey("RiscattataDaUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcquirenteUser");

                    b.Navigation("Ordine");

                    b.Navigation("RiscattataDaUser");
                });

            modelBuilder.Entity("FilmAPI.Model.ManualRefundReview", b =>
                {
                    b.HasOne("FilmAPI.Model.Ordine", "Ordine")
                        .WithMany()
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId");

                    b.HasOne("FilmAPI.Model.ShowCancellation", "ShowCancellation")
                        .WithMany()
                        .HasForeignKey("ShowCancellationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordine");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("ShowCancellation");
                });

            modelBuilder.Entity("FilmAPI.Model.MembershipCard", b =>
                {
                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.MerchOrder", b =>
                {
                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.MerchOrderItem", b =>
                {
                    b.HasOne("FilmAPI.Model.MerchItem", "MerchItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MerchItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.MerchOrder", "MerchOrder")
                        .WithMany("Items")
                        .HasForeignKey("MerchOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MerchItem");

                    b.Navigation("MerchOrder");
                });

            modelBuilder.Entity("FilmAPI.Model.MovimentoCredito", b =>
                {
                    b.HasOne("FilmAPI.Model.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FilmAPI.Model.User", "OperatoreUser")
                        .WithMany()
                        .HasForeignKey("OperatoreUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FilmAPI.Model.Ordine", "Ordine")
                        .WithMany()
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("OperatoreUser");

                    b.Navigation("Ordine");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.Ordine", b =>
                {
                    b.HasOne("FilmAPI.Model.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Show", "Show")
                        .WithMany("Ordini")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany("Ordini")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Film");

                    b.Navigation("Sala");

                    b.Navigation("Show");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.OrdineRefund", b =>
                {
                    b.HasOne("FilmAPI.Model.Ordine", "Ordine")
                        .WithMany()
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.ShowCancellation", "ShowCancellation")
                        .WithMany()
                        .HasForeignKey("ShowCancellationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ordine");

                    b.Navigation("ShowCancellation");
                });

            modelBuilder.Entity("FilmAPI.Model.PartyBooking", b =>
                {
                    b.HasOne("FilmAPI.Model.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId");

                    b.HasOne("FilmAPI.Model.Ordine", "Ordine")
                        .WithMany()
                        .HasForeignKey("OrdineId");

                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Film");

                    b.Navigation("Ordine");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.PartyFeedback", b =>
                {
                    b.HasOne("FilmAPI.Model.PartyBooking", "PartyBooking")
                        .WithMany()
                        .HasForeignKey("PartyBookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyBooking");
                });

            modelBuilder.Entity("FilmAPI.Model.PasswordResetToken", b =>
                {
                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.PremioRiscatto", b =>
                {
                    b.HasOne("FilmAPI.Model.Premio", "Premio")
                        .WithMany()
                        .HasForeignKey("PremioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Premio");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.Prenotazione", b =>
                {
                    b.HasOne("FilmAPI.Model.Proiezione", "Proiezione")
                        .WithMany()
                        .HasForeignKey("ProiezioneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proiezione");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.Proiezione", b =>
                {
                    b.HasOne("FilmAPI.Model.Cinema", "Cinema")
                        .WithMany("Proiezioni")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Film", "Film")
                        .WithMany("Proiezioni")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("FilmAPI.Model.PuntiMovimento", b =>
                {
                    b.HasOne("FilmAPI.Model.MembershipCard", "MembershipCard")
                        .WithMany()
                        .HasForeignKey("MembershipCardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MembershipCard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.ReferralCode", b =>
                {
                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.RefreshToken", b =>
                {
                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.Sala", b =>
                {
                    b.HasOne("FilmAPI.Model.Cinema", "Cinema")
                        .WithMany("Sale")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("FilmAPI.Model.SalaPosto", b =>
                {
                    b.HasOne("FilmAPI.Model.Sala", "Sala")
                        .WithMany("Posti")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("FilmAPI.Model.Show", b =>
                {
                    b.HasOne("FilmAPI.Model.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Film", "Film")
                        .WithMany("Shows")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Sala", "Sala")
                        .WithMany("Shows")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Film");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("FilmAPI.Model.ShowCancellation", b =>
                {
                    b.HasOne("FilmAPI.Model.User", "CancelledByUser")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Show", "Show")
                        .WithMany()
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CancelledByUser");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("FilmAPI.Model.ShowPostoStato", b =>
                {
                    b.HasOne("FilmAPI.Model.Ordine", "Ordine")
                        .WithMany()
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FilmAPI.Model.SalaPosto", "SalaPosto")
                        .WithMany()
                        .HasForeignKey("SalaPostoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.Show", "Show")
                        .WithMany("PostiStato")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ordine");

                    b.Navigation("SalaPosto");

                    b.Navigation("Show");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.SupportConversation", b =>
                {
                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany("SupportConversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.SupportMessage", b =>
                {
                    b.HasOne("FilmAPI.Model.SupportConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.SupportTicket", b =>
                {
                    b.HasOne("FilmAPI.Model.User", "AssignedAdminUser")
                        .WithMany()
                        .HasForeignKey("AssignedAdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FilmAPI.Model.SupportConversation", "Conversation")
                        .WithMany("Tickets")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany("SupportTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedAdminUser");

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.SupportTicketAudit", b =>
                {
                    b.HasOne("FilmAPI.Model.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FilmAPI.Model.SupportTicket", "Ticket")
                        .WithMany("Audits")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("FilmAPI.Model.User", b =>
                {
                    b.HasOne("FilmAPI.Model.Cinema", "CinemaPreferito")
                        .WithMany()
                        .HasForeignKey("CinemaPreferitoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CinemaPreferito");
                });

            modelBuilder.Entity("FilmAPI.Model.UserCinemaAssignment", b =>
                {
                    b.HasOne("FilmAPI.Model.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FilmAPI.Model.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FilmAPI.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("CreatedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmAPI.Model.Categoria", b =>
                {
                    b.Navigation("FilmCategorie");
                });

            modelBuilder.Entity("FilmAPI.Model.Cinema", b =>
                {
                    b.Navigation("Proiezioni");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("FilmAPI.Model.Film", b =>
                {
                    b.Navigation("FilmCategorie");

                    b.Navigation("Proiezioni");

                    b.Navigation("Shows");
                });

            modelBuilder.Entity("FilmAPI.Model.MerchItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FilmAPI.Model.MerchOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FilmAPI.Model.Ordine", b =>
                {
                    b.Navigation("Biglietti");
                });

            modelBuilder.Entity("FilmAPI.Model.Regista", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("FilmAPI.Model.Sala", b =>
                {
                    b.Navigation("Posti");

                    b.Navigation("Shows");
                });

            modelBuilder.Entity("FilmAPI.Model.Show", b =>
                {
                    b.Navigation("Biglietti");

                    b.Navigation("Ordini");

                    b.Navigation("PostiStato");
                });

            modelBuilder.Entity("FilmAPI.Model.SupportConversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("FilmAPI.Model.SupportTicket", b =>
                {
                    b.Navigation("Audits");
                });

            modelBuilder.Entity("FilmAPI.Model.User", b =>
                {
                    b.Navigation("Biglietti");

                    b.Navigation("Ordini");

                    b.Navigation("Prenotazioni");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SupportConversations");

                    b.Navigation("SupportTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
